version: '3.8'

services:
  todo-app:
    restart: always
    container_name: todo-app
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - ${TODO_APP_PORT}:3000
    env_file:
      - ./.env
