version: '3.8'

services:
  todo-app:
    restart: always
    container_name: todo-app
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - ${TODO_APP_PORT}:3000
    volumes:
      - ./:/usr/todo-app
      - /usr/todo-app/node_modules
      - /user/todo-app/.next
    env_file:
      - ./.env
