
FROM node:17-alpine

COPY package.json ./
RUN npm install

COPY . .
RUN npm run build


ENV NODE_ENV production

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

USER nextjs

CMD ["npm", "run", "start"]